name: Update Readme
description: Updates Readme with template

inputs:
  readme_path:
    description: Path to readme file
    required: true
    default: ./README.md

runs:
  using: "node20"
  main: "dist/index.js"
