name: Update Readme

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update Readme
        uses: readmeupdate@v1
        with:
          readme_path: README.md
